base_url = "https://www.tokyorust.org"
compile_sass = true
build_search_index = true
default_language = "en"

[markdown]
highlight_code = true

[languages.jp]

[extra]
events_page_link = "https://www.meetup.com/tokyo-rust-meetup/"
