name: Test Static Site Links
description: Test a built static site locally (not the deployed version)
runs:
  using: composite
  steps:
    - name: Check Links
      id: lychee
      uses: lycheeverse/lychee-action@v1
      with:
        args: --accept 200,429 --base ./static-site/public ./static-site/public
        jobSummary: true
        fail: true
