name: Build and Publish to AWS
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - static-site/**

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Build The Site
        id: build
        uses: "./.github/actions/build-static"

      - name: Check Links
        id: lychee
        uses: "./.github/actions/check-links"

      - name: Configure AWS Credentials
        id: configure-aws-creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.STATIC_DEPLOYER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STATIC_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy static site to S3 bucket
        id: deploy-to-s3
        run: aws s3 sync ./static-site/public s3://${{ vars.S3_BUCKET }} --delete
